os: linux
dist: xenial
sudo: required
services: docker
env: DOCKER_IMAGE=swift:4.2.4 SWIFT_SNAPSHOT=4.2.4

install: . CI/install.sh

script:
  - swiftlint
  - swift build
  - swift test

deploy:
  provider: script
  script: CI/release-version.sh
  on:
    branch: master
