os: linux
dist: trusty
sudo: required

before_install:
- sudo apt-get update

install: . CI/install.sh

script:
  - swiftlint
  - swift build
  - swift test

deploy:
  provider: script
  script: CI/release-version.sh
  on:
    branch: master
