language: generic
sudo: required
dist: trusty
env:
- SWIFT_VERSION=swift-2.2-SNAPSHOT-2015-12-01-b

install: . CI/install.sh

script:
  - swiftlint
  - swift build
  - swift test

deploy:
  provider: script
  script: CI/release-version.sh
  on:
    branch: master
