image: swift:4.2.3

pipelines:
    default:
        - step:
            script:
                - ./CI/install.sh
                - swiftlint
                - swift test
            services:
                - postgres
    branches:
        master:
            - step:
                name: Testing
                script:
                    - ./CI/install.sh
                    - swiftlint
                    - swift test
                services:
                    - postgres
            - step:
                name: Release
                script:
                    - ./CI/release-version.sh

definitions: 
    services:
        postgres:
            image: postgres
