image: swift:4.2.3

test: &test
    step:
        name: Test
        script:
            - ./CI/install.sh
            - swiftlint
            - swift test
        services:
            - postgres

pipelines:
    default:
    - <<: *test
    branches:
        master:
            - <<: *test
            - step:
                name: Release
                script:
                    - ./CI/release-version.sh

definitions: 
    services:
        postgres:
            image: postgres
