image: swift:4.2.3

clone:
  depth: full

pipelines:
  default:
    - step:
        script:
          - . CI/install.sh
          - swiftlint
          - swift test || true
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
        services: 
          - postgres
  branches:
    master:
      - step:
        name: Release
        script:
          - . CI/release-version.sh

definitions: 
  services: 
    postgres: 
      image: postgres
