image: swift:4.2.3

clone:
  depth: full

pipelines:
  default:
    - step:
        script:
          - git clone https://github.com/realm/SwiftLint.git
          - cd SwiftLint
          - swift build -c release --static-swift-stdlib
          - mv .build/x86_64-unknown-linux/release/swiftlint /usr/local/bin/
          - cd ..
          - rm -rf SwiftLint
          - swift package resolve
          - swift package clean
          - swiftlint
          - swift test || true
        services: 
          - postgres

definitions: 
  services: 
    postgres: 
      image: postgres
